on: [ push, pull_request ]

name: ci

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install target
        run: rustup target add thumbv7em-none-eabihf

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose